/**
 * disciplines/system/ch05_acceptance.js
 *
 * System Chapter 4 (display) — Acceptance Requirements (Black-Box).
 * The external contract. Subject is always "the system". Mode-driven
 * EARS requirements generated by ch06_breakdown's generator land here.
 */

Chapters.register('system', {
    id: 'ch05_acceptance',
    number: '3',
    title: 'Acceptance Requirements (Black-Box Layer)',
    order: 60,
    intro: 'The external contract. Subject is always "the system". Tight budget.',
    allowsRequirements: true,
    subjectMode: 'system',
    requirementBudget: { min: 10, max: 60 },
    checklist: [
        { id: 'c5a', text: 'Functional acceptance count within 10–20.',
          help: 'Below 10 = under-specified; above 20 = mixing functional with non-functional, split them out.' },
        { id: 'c5b', text: 'Non-functional acceptance count within ≤40.',
          help: 'Above 40 usually indicates duplication; consolidate.' },
        { id: 'c5c', text: 'Every item function has ≥1 acceptance requirement.',
          help: 'Right-pane Item Functions section shows A:N counts.' },
        { id: 'c5d', text: 'Every Safety Goal has ≥1 acceptance requirement addressing it.',
          help: 'Acceptance requirements trace via parentFsrs → FSR → parentSG → SG.' },
        { id: 'c5e', text: 'Every acceptance requirement has subject = "the system".',
          help: 'Black-box layer: never about internal elements.' },
        { id: 'c5f', text: 'Every acceptance requirement has source, rationale, verification method, pass criterion.',
          help: 'All four collected by the acceptance attribute panel.' },
        { id: 'c5g', text: 'ASIL-relevant acceptance requirements carry ASIL, parent SG, FTTI, safe state.' },
        { id: 'c5h', text: 'No acceptance requirement references an undeclared element.',
          help: 'Right-pane orphan report flags broken refs.' }
    ]
});
